SELECT COUNT(V) FROM
(
 SELECT V FROM dual 
 MODEL DIMENSION BY (0 AS R) 
			MEASURES (0 AS V) 
			RULES ITERATE (10) (
				V[ITERATION_NUMBER]=ITERATION_NUMBER + 1
			)
 ORDER BY 1
 );
 
 SELECT ROWNUM FROM 
 (
  SELECT 1 AS c FROM dual 
  GROUP BY CUBE(1,1,1,1,1,1,1,1)
 )
 WHERE ROWNUM <=1000;
  
 SELECT ROWNUM AS R FROM DUAL CONNECT BY ROWNUM <=10;
  
  
  
  INSERT /*APPEND*/ INTO HI_CARD_KYK_CST_KANREN(KYK_CST_KANREN_NO, CARD_NO,
IKO_SIGN, DELETE_SIGN, DELETE_DATE, INSERT_USER_ID, INSERT_DATE_TIME,
UPDATE_USER_ID, UPDATE_DATE_TIME, MEM_NO, CST_NO, MOSIKOMI_NO,
KYK_KANREN_CST_ATTR_KBN, KYK_FORM_KBN, KYK_STS_KBN, KYK_DELETE_SIGN,
CARD_HAKKO_SIGN) SELECT TO_CHAR(20000136+rownum, '00000000000'), CARD_NO, IKO_SIGN,
DELETE_SIGN, DELETE_DATE, INSERT_USER_ID, INSERT_DATE_TIME, UPDATE_USER_ID,
UPDATE_DATE_TIME, MEM_NO, CST_NO, MOSIKOMI_NO, KYK_KANREN_CST_ATTR_KBN,
KYK_FORM_KBN, KYK_STS_KBN, KYK_DELETE_SIGN, CARD_HAKKO_SIGN FROM (SELECT
CARD_NO, IKO_SIGN, DELETE_SIGN, DELETE_DATE, INSERT_USER_ID, INSERT_DATE_TIME,
UPDATE_USER_ID, UPDATE_DATE_TIME, MEM_NO, CST_NO, MOSIKOMI_NO,
KYK_KANREN_CST_ATTR_KBN, KYK_FORM_KBN, KYK_STS_KBN, KYK_DELETE_SIGN,
CARD_HAKKO_SIGN FROM HI_CARD_KYK_CST_KANREN ORDER BY KYK_CST_KANREN_NO) WHERE
rownum <= 2