SELECT COUNT(V) FROM
(
 SELECT V FROM dual 
 MODEL DIMENSION BY (0 AS R) 
			MEASURES (0 AS V) 
			RULES ITERATE (10) (
				V[ITERATION_NUMBER]=ITERATION_NUMBER + 1
			)
 ORDER BY 1
 );
 
 SELECT ROWNUM FROM 
 (
  SELECT 1 AS c FROM dual 
  GROUP BY CUBE(1,1,1,1,1,1,1,1)
 )
 WHERE ROWNUM <=1000;
  
 SELECT ROWNUM AS R FROM DUAL CONNECT BY ROWNUM <=10;
  